apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: qa
type: Opaque
data:
  config.json: ewogICAgImFjY2Vzc0tleUlkIjogIkFLSUFaR0RES0VGTElZM0VWRUhIIiwKICAgICJzZWNyZXRBY2Nlc3NLZXkiOiAidmF6aFliVml0SDkzZG1YRk1oOGtLT3VYbzROUzA2UkhmN0sxYUxYSCIsCiAgICAicmVnaW9uIjogImFwLXNvdXRoZWFzdC0xIgp9