apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: uat
type: Opaque
data:
  config.json: eyAKICAgICJhY2Nlc3NLZXlJZCI6ICJBS0lBWTJMS0VFWElVRkZCUVQ2TSIsCiAgICAic2VjcmV0QWNjZXNzS2V5IjogInJFaDZad2VMYWlLSEF3aWZlY3VxeDc4RUhqWEVJbGk3aC9VNjdRVjIiLAogICAgInJlZ2lvbiI6ICJhcC1zb3V0aGVhc3QtMSIKfQ==